# Generated by Django 4.0 on 2024-01-17 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='slug_category_product',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
