# Generated by Django 4.0 on 2024-01-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categoryproduct_slug_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='slug_category_product',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
